apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mern-backend
  template:
    metadata:
      labels:
        app: mern-backend
    spec:
      containers:
        - name: mern-backend
          image: tejasreelokireddy/mern-backend:latest
          ports:
            - containerPort: 3000
